# SPDX-FileCopyrightText: 2026 {{ cookiecutter.author }}
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "{{ cookiecutter.project_slug }}"
SPDX-PackageSupplier = "https://github.com/{{ cookiecutter.github_author }}/{{ cookiecutter.project_slug }}"

# Configuration files that don't require copyright/license headers in the file itself
# These are annotated here with MIT (same as the rest of the project)
[[annotations]]
path = "uv.lock"
SPDX-FileCopyrightText = "N/A"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "uv.lock file"

[[annotations]]
path = ".python-version"
SPDX-FileCopyrightText = "N/A"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "Python version file"
